# Tankerkoenig user configuration
# Get your personal API key from https://creativecommons.tankerkoenig.de/
apikey=
location=Berlin
latitude=52.5200
longitude=13.4050
radius=10
fuel=e10
sort=price
open_only=0
update_minutes=10
